from tkinter import *
window = Tk()
window.title("sample window")
window.geometry("1000x500")
greeting = Label(text = 'hello user',fg = 'green',bg = 'red')
btn = Button(text = 'click me',fg = 'black',bg = "white")
a = Entry(fg = 'black',bg = 'red',width = 50)
box = Text(fg = 'gray',bg = 'blue')
greeting.pack()
btn.pack()
a.pack()
box.pack()
frame = Frame(master = window,relief = RAISED,borderwidth = 5)
label = Label(master = frame,text = "sample")
label.pack()
window.mainloop()